<img src='./NumPy_logo.png'/>

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Print the numpy version and the configuration

In [2]:
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Hamza/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Hamza/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Hamza/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

3. Create a null vector of size 10

In [3]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to get the documentation of the numpy add function from the command line?

In [4]:
# python -c "import numpy; numpy.info(numpy.add)"
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

5. Create a null vector of size 10 but the fifth value which is 1

In [5]:
z = np.zeros(10)
z[4] = 1
print(z)
z

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

6. Create a vector with values ranging from 10 to 49

In [6]:
vrange = np.arange(10,50)
print(vrange)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


7. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
vect = np.arange(1,11)
print('vector before :',vect)
vect = vect[::-1]
print('vector after :', vect)

vector before : [ 1  2  3  4  5  6  7  8  9 10]
vector after : [10  9  8  7  6  5  4  3  2  1]


8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
matrix = np.arange(0,9).reshape((3,3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

numpy.nonzero(a)
Return the indices of the elements that are non-zero.

Returns a tuple of arrays, one for each dimension of a, containing the indices of the non-zero elements in that dimension. The values in a are always tested and returned in row-major, C-style order.

In [9]:
# v = np.array([1,2,0,0,4,0])
# nz = v[v != 0]
# print(nz)
########
x = np.array([1,2,0,0,4,0])
nz = np.nonzero(x)
print('index of non-zeros :',nz)
print(x[nz])

index of non-zeros : (array([0, 1, 4], dtype=int64),)
[1 2 4]


10. Create a 3x3 identity matrix (★☆☆)

In [10]:
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


11. Create a 3x3x3 array with random values (★☆☆)

In [11]:
rm = np.random.random((3,3,3))
rm2 = np.random.rand(3,3,3)
print(rm)
print('---------------------------------------------------------')
print(rm2)

[[[0.25491033 0.18503924 0.5686456 ]
  [0.782384   0.00674751 0.92173137]
  [0.01057596 0.84909149 0.86483112]]

 [[0.43330694 0.93269867 0.88437284]
  [0.1520923  0.13307582 0.62008307]
  [0.7749382  0.3614731  0.59956951]]

 [[0.88045823 0.81977947 0.25064128]
  [0.4861138  0.84979254 0.81060565]
  [0.18199261 0.69615987 0.41429592]]]
---------------------------------------------------------
[[[0.07529707 0.47751398 0.85263707]
  [0.04035091 0.26380356 0.20407569]
  [0.32889047 0.03529902 0.80129029]]

 [[0.60996105 0.42506913 0.53095877]
  [0.86333092 0.94596953 0.29376012]
  [0.0615505  0.55498426 0.73587693]]

 [[0.53670472 0.42485867 0.18019901]
  [0.62766971 0.81090945 0.20060015]
  [0.74190612 0.38484619 0.73747748]]]


12. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [12]:
rm = np.random.random((10,10))
rMax, rMin = rm.max(), rm.min()
print('random matrix:', rm)
print('----------------------------------------------------------')
print('maximum :', rMax)
print('minimum :', rMin)

random matrix: [[0.21856336 0.50621488 0.86540188 0.72153784 0.73451859 0.88104097
  0.72886195 0.32522951 0.400966   0.03648071]
 [0.53477462 0.81346626 0.173681   0.66928123 0.64985683 0.73753272
  0.53814092 0.3695959  0.82918562 0.65332501]
 [0.62736287 0.64883862 0.3102882  0.16798581 0.62681682 0.89099283
  0.63787197 0.81599786 0.49263936 0.47515029]
 [0.54341104 0.47349883 0.40298069 0.90920986 0.77040145 0.41813802
  0.31190082 0.11199189 0.70431048 0.67286928]
 [0.35446998 0.87167083 0.86711088 0.62047439 0.74385784 0.80061867
  0.11602877 0.66745875 0.80192633 0.3281931 ]
 [0.21971923 0.86729288 0.05077748 0.91216865 0.23548715 0.74724599
  0.06463878 0.76654016 0.52145009 0.74555729]
 [0.93398816 0.40371791 0.51854322 0.03882316 0.04155729 0.09341192
  0.55322471 0.69094974 0.8800306  0.68261706]
 [0.68964329 0.68011442 0.47795626 0.01195627 0.20307093 0.38292066
  0.93295857 0.72695056 0.32094033 0.934885  ]
 [0.110595   0.16702504 0.4616901  0.48083961 0.85607027 0.929379

13. Create a random vector of size 30 and find the mean value (★☆☆)

In [13]:
rv = np.random.random(30)
rMean = rv.mean()
print('random vector:', rv)
print('----------------------------------------------------------')
print('vector mean :', rMean)

random vector: [0.34051617 0.57306977 0.1036867  0.20518409 0.22718903 0.26764425
 0.58947714 0.61990759 0.65264292 0.25001838 0.72247894 0.56607189
 0.92634996 0.61228921 0.97069732 0.08409541 0.68889997 0.35448497
 0.9130292  0.21749411 0.991782   0.8431042  0.627157   0.2931404
 0.12596963 0.56209396 0.5526299  0.63571353 0.78314931 0.62119957]
----------------------------------------------------------
vector mean : 0.5307055520228936


14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [14]:
arr2d = np.zeros((5,5))
arr2d[0, :] = 1
arr2d[-1, :] = 1
arr2d[:, 0] = 1
arr2d[:, -1] = 1
print(arr2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
z = np.ones((10,10))
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


15. What is the result of the following expression? (★☆☆)

In [16]:
# 0 * np.nan #0 --> nan
# np.nan == np.nan #True --> False
# np.inf > np.nan #Error --> False
# np.nan - np.nan # np.nan
0.3 == 3*0.1 #True --> False:(Discussion)https://www.sololearn.com/Discuss/1477626/error-in-python-0-1-0-2-not-equal-0-3

False

16. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [17]:
z = np.diag(1+np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [18]:
z = np.ones((8,8))
z[0::2, 0::2] = 0
z[1::2, 1::2] = 0
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [19]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
z = np.arange(1,6*7*8+1).reshape((6,7,8))
print(np.where(z == 100))

(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))


In [21]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [22]:
np.info(np.unravel_index)

 unravel_index(*args, **kwargs)

unravel_index(indices, shape, order='C')

Converts a flat index or array of flat indices into a tuple
of coordinate arrays.

Parameters
----------
indices : array_like
    An integer array whose elements are indices into the flattened
    version of an array of dimensions ``shape``. Before version 1.6.0,
    this function accepted just one index value.
shape : tuple of ints
    The shape of the array to use for unraveling ``indices``.

    .. versionchanged:: 1.16.0
        Renamed from ``dims`` to ``shape``.

order : {'C', 'F'}, optional
    Determines whether the indices should be viewed as indexing in
    row-major (C-style) or column-major (Fortran-style) order.

    .. versionadded:: 1.6.0

Returns
-------
unraveled_coords : tuple of ndarray
    Each array in the tuple has the same shape as the ``indices``
    array.

See Also
--------
ravel_multi_index

Examples
--------
>>> np.unravel_index([22, 41, 37], (7,6))
(array([3, 6, 6]), array([4, 5, 1])

19. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
cb = np.array([[0,1],[1,0]], dtype=int)
print(np.tile(cb,(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Normalize a 5x5 random matrix (★☆☆)

In [25]:
Z = np.random.randn(5,5)
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin) 
print(Z)

[[0.8796983  0.87916074 0.24937535 0.85673026 0.44697549]
 [0.78579215 0.55493027 0.77107183 0.52522109 0.29442818]
 [0.31909822 0.67908503 0.24823299 0.26964373 0.48552687]
 [0.02190064 0.75973564 0.34087432 1.         0.4182051 ]
 [0.15262682 0.56293983 0.34713747 0.56858802 0.        ]]


21. Create a custom dtype that describes a color as four unisgned bytes (RGBA) (★☆☆)

In [26]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

C:\Users\Hamza\anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


22. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [38]:
A = np.random.randint(0,20,(5,3))
B = np.random.randint(0,20,(3,2))
C = np.dot(A,B)

In [41]:
C

array([[340, 391],
       [380, 374],
       [290, 211],
       [535, 435],
       [340, 286]])

23. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [43]:
Z = np.random.randint(1,10,(10,1))
Z

array([[5],
       [7],
       [5],
       [6],
       [6],
       [1],
       [8],
       [1],
       [1],
       [3]])

In [44]:
Z[(Z>=3) & (Z<=8)] *= -1

In [45]:
Z

array([[-5],
       [-7],
       [-5],
       [-6],
       [-6],
       [ 1],
       [-8],
       [ 1],
       [ 1],
       [-3]])

24. What is the output of the following script? (★☆☆)

In [53]:
# print(sum(range(5),-5))
print(sum(range(5),-1))
print(np.sum(range(5),-1))

9
10


25. Consider an integer vector Z, which of these expressions are legal?(★☆☆)

In [56]:
Z = np.random.randint(0,5,(3,1))
Z

array([[0],
       [1],
       [4]])

In [60]:
# Z**Z
# 2 << Z >> 2 #https://stackoverflow.com/questions/22832615/what-do-and-mean-in-python
# Z <- Z
# 1j*Z
# Z/1/1
# Z<Z>Z

array([[0],
       [1],
       [8]], dtype=int32)