# Artificial Neural Network

<img src='Stochastic_Gradient_Descent.png' />

In [30]:
import numpy as np
import pandas as pd
import tensorflow as tf

# Part I : Data Preprocessing

## Importing the  dataset

In [31]:
import os
os.listdir()

['.ipynb_checkpoints',
 'artificial_neural_network.ipynb',
 'artificial_neural_network.py',
 'artificiel_neural_network_hamza.ipynb',
 'Churn_Modelling.csv',
 'Stochastic_Gradient_Descent.png']

In [32]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [33]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, -1].values

In [34]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [35]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encodding the "Gender" column

In [36]:
from sklearn.preprocessing import LabelEncoder

In [37]:
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [38]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [39]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [40]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Feature Scaling

In [41]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
print(X)

[[ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167  0.97024255
   0.02188649]
 [-1.00280393 -0.57873591  1.74273971 ... -1.54776799  0.97024255
   0.21653375]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [ 0.99720391 -0.57873591 -0.57380915 ... -1.54776799  0.97024255
  -1.00864308]
 [-1.00280393  1.72790383 -0.57380915 ...  0.64609167 -1.03067011
  -0.12523071]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
  -1.07636976]]


In [42]:
print(X.shape)

(10000, 12)


### Avoiding the dummy variable trap

In [43]:
X = X[:,1:]

### Splitting the dataset into the Training set and Test set

In [44]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(X,y, test_size=1/4, random_state=42)

## Part 2 - Building the ANN

###  Initializing the ANN

In [45]:
ann = tf.keras.models.Sequential()

In [46]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [47]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [48]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [50]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [53]:
ann.fit(Xtrain, ytrain, batch_size = 32, epochs = 100)

Epoch 1/100
7500/7500 [==============================] - 0s 23us/sample - loss: 0.3334 - acc: 0.8632
Epoch 2/100
7500/7500 [==============================] - 0s 21us/sample - loss: 0.3337 - acc: 0.8608
Epoch 3/100
7500/7500 [==============================] - 0s 22us/sample - loss: 0.3334 - acc: 0.8632
Epoch 4/100
7500/7500 [==============================] - 0s 21us/sample - loss: 0.3332 - acc: 0.8621
Epoch 5/100
7500/7500 [==============================] - 0s 21us/sample - loss: 0.3333 - acc: 0.8631
Epoch 6/100
7500/7500 [==============================] - 0s 21us/sample - loss: 0.3332 - acc: 0.8631
Epoch 7/100
7500/7500 [==============================] - 0s 22us/sample - loss: 0.3330 - acc: 0.8639
Epoch 8/100
7500/7500 [==============================] - 0s 21us/sample - loss: 0.3330 - acc: 0.8624
Epoch 9/100
7500/7500 [==============================] - 0s 22us/sample - loss: 0.3331 - acc: 0.8619
Epoch 10/100
7500/7500 [==============================] - 0s 21us/sample - loss: 0.3334 - a

7500/7500 [==============================] - 0s 20us/sample - loss: 0.3313 - acc: 0.8651
Epoch 82/100
7500/7500 [==============================] - 0s 20us/sample - loss: 0.3316 - acc: 0.8637
Epoch 83/100
7500/7500 [==============================] - 0s 20us/sample - loss: 0.3316 - acc: 0.8641
Epoch 84/100
7500/7500 [==============================] - 0s 21us/sample - loss: 0.3313 - acc: 0.8640
Epoch 85/100
7500/7500 [==============================] - 0s 23us/sample - loss: 0.3313 - acc: 0.8640
Epoch 86/100
7500/7500 [==============================] - 0s 21us/sample - loss: 0.3314 - acc: 0.8644
Epoch 87/100
7500/7500 [==============================] - 0s 21us/sample - loss: 0.3311 - acc: 0.8647
Epoch 88/100
7500/7500 [==============================] - 0s 23us/sample - loss: 0.3316 - acc: 0.8640
Epoch 89/100
7500/7500 [==============================] - 0s 23us/sample - loss: 0.3313 - acc: 0.8644
Epoch 90/100
7500/7500 [==============================] - 0s 23us/sample - loss: 0.3312 - acc: 

In [56]:
ypred = ann.predict(Xtest)
ypred = (ypred > 0.5)
print(np.concatenate((ypred.reshape(len(ypred),1), ytest.reshape(len(ytest),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [58]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest, ypred)
print(cm)

[[1922   81]
 [ 259  238]]


### Importing the Keras libraries and packages

In [17]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


###  Initializing the ANN

In [19]:
classifier = Sequential()

###  Adding the input layer and the first hidden layer

In [20]:
classifier.add(Dense(output_dim=6, init='uniform', activation='relu', input_dim=11))
classifier.add(Dense(output_dim=6, init='uniform', activation='relu'))

D:\Program Files\anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.
D:\Program Files\anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


###  Adding the ouput layer

In [21]:
classifier.add(Dense(output_dim=1, init='uniform', activation='sigmoid'))

D:\Program Files\anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


### Compiling the ANN

In [22]:
classifier.compile(optimizer="adam", loss='binary_crossentropy', metrics = ['accuracy'])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


### Fitting the ANN to the Training set

In [23]:
classifier.fit(Xtrain, ytrain, batch_size=10, nb_epoch = 100)

D:\Program Files\anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.



Epoch 1/100
7500/7500 [==============================] - 2s 216us/step - loss: 0.4902 - accuracy: 0.7943
Epoch 2/100
7500/7500 [==============================] - 3s 417us/step - loss: 0.4325 - accuracy: 0.7947
Epoch 3/100
7500/7500 [==============================] - 3s 413us/step - loss: 0.4255 - accuracy: 0.8012
Epoch 4/100
7500/7500 [==============================] - 3s 417us/step - loss: 0.4175 - accuracy: 0.8288
Epoch 5/100
7500/7500 [==============================] - 3s 390us/step - loss: 0.4122 - accuracy: 0.8321
Epoch 6/100
7500/7500 [==============================] - 2s 315us/step - loss: 0.4082 - accuracy: 0.8323
Epoch 7/100
7500/7500 [==============================] - 1s 133us/step - loss: 0.4063 - accuracy: 0.8335
Epoch 8/100
7500/7500 [==============================] - 3s 374us/step - loss: 0.4048 - accuracy: 0.8340
Epoch 9/100
7500/7500 [==============================] - 3s 391us/step - loss: 0.4035 - accuracy: 0.8331
Epoch 10/100
7500/7500 [==============================

### Predicting the test results

In [24]:
ypred = classifier.predict(Xtest)
print(ypred)

[[0.02713695]
 [0.02194929]
 [0.15064013]
 ...
 [0.00179288]
 [0.14323308]
 [0.06427712]]


In [25]:
ypred = (ypred > 0.5)

### Making the Confusion Matrix

In [29]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest,ypred)
print(cm)

[[1937   66]
 [ 274  223]]
