# multiple linear regression

## Importing the libraries

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [8]:
import os
os.listdir()

['.ipynb_checkpoints',
 '50_Startups.csv',
 'multiple_linear_regression.ipynb',
 'multiple_linear_regression.py',
 'multiple_linear_regression_hamza.ipynb']

In [9]:
dataset = pd.read_csv('50_Startups.csv')
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [10]:
# independante varaibles
X = dataset.iloc[:,:4].values
#X

In [11]:
# dependante variable
y = dataset.iloc[:,4:5].values
print(y)

[[192261.83]
 [191792.06]
 [191050.39]
 [182901.99]
 [166187.94]
 [156991.12]
 [156122.51]
 [155752.6 ]
 [152211.77]
 [149759.96]
 [146121.95]
 [144259.4 ]
 [141585.52]
 [134307.35]
 [132602.65]
 [129917.04]
 [126992.93]
 [125370.37]
 [124266.9 ]
 [122776.86]
 [118474.03]
 [111313.02]
 [110352.25]
 [108733.99]
 [108552.04]
 [107404.34]
 [105733.54]
 [105008.31]
 [103282.38]
 [101004.64]
 [ 99937.59]
 [ 97483.56]
 [ 97427.84]
 [ 96778.92]
 [ 96712.8 ]
 [ 96479.51]
 [ 90708.19]
 [ 89949.14]
 [ 81229.06]
 [ 81005.76]
 [ 78239.91]
 [ 77798.83]
 [ 71498.49]
 [ 69758.98]
 [ 65200.33]
 [ 64926.08]
 [ 49490.75]
 [ 42559.73]
 [ 35673.41]
 [ 14681.4 ]]


## Encoding Categorical Data

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

## Avoiding the dummy variables trap

In [13]:
X = X[:,1:]
X

array([[0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [1.0, 0.0, 91749.16, 114175.79, 294919.57],
       [0.0, 1.0, 86419.7

## Spliting the dataset to training set and test set

In [14]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2)

C:\Users\Hamza\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [15]:
Xtrain

array([[0.0, 0.0, 0.0, 135426.92, 0.0],
       [1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 1.0, 1000.23, 124153.04, 1903.93],
       [0.0, 0.0, 63408.86, 129219.61, 46085.25],
       [0.0, 0.0, 44069.95, 51283.14, 197029.42],
       [0.0, 1.0, 542.05, 51743.15, 0.0],
       [0.0, 0.0, 76253.86, 113867.3, 298664.47],
       [0.0, 1.0, 61136.38, 152701.92, 88218.23],
       [0.0, 1.0, 86419.7, 153514.11, 0.0],
       [1.0, 0.0, 67532.53, 105751.03, 304768.73],
       [1.0, 0.0, 91749.16, 114175.79, 294919.57],
       [0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 22177.74, 154806.14, 28334.72],
       [0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [0.0, 1.0, 15505.73, 127382.3, 35534.17],
       [1.0, 0.0, 1315.46, 115816.21, 297114.46],
       [0.0, 0.0, 1

## Training the Multiple Linear Regression on the training set

In [16]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

In [17]:
regressor.fit(Xtrain, ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Predicting the test set results

In [18]:
ypred = regressor.predict(Xtest)
ypred

array([[ 73993.76134372],
       [ 99619.38609856],
       [111060.94305219],
       [114693.81934063],
       [101772.35972515],
       [146177.41904899],
       [ 69566.63150852],
       [135511.39819345],
       [173489.43170106],
       [ 89966.60861046]])

In [19]:
ytest

array([[ 78239.91],
       [ 99937.59],
       [105733.54],
       [110352.25],
       [107404.34],
       [129917.04],
       [ 71498.49],
       [146121.95],
       [182901.99],
       [ 96479.51]])

In [20]:
np.set_printoptions(precision=2)
print(np.concatenate((ypred.reshape(len(ypred),1), ytest.reshape(len(ytest),1)),1))

[[ 73993.76  78239.91]
 [ 99619.39  99937.59]
 [111060.94 105733.54]
 [114693.82 110352.25]
 [101772.36 107404.34]
 [146177.42 129917.04]
 [ 69566.63  71498.49]
 [135511.4  146121.95]
 [173489.43 182901.99]
 [ 89966.61  96479.51]]


## Building the optimal model using Backward Elimination

In [21]:
# add B0 constant column
X = np.append(arr= np.ones((50,1)), values=X, axis=1)
print(X)

[[1.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [1.0 1.0 0.0 153441.51 101145.55 407934.54]
 [1.0 0.0 1.0 144372.41 118671.85 383199.62]
 [1.0 1.0 0.0 142107.34 91391.77 366168.42]
 [1.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [1.0 1.0 0.0 130298.13 145530.06 323876.68]
 [1.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [1.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [1.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [1.0 1.0 0.0 119943.24 156547.42 256512.92]
 [1.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [1.0 0.0 1.0 94657.16 145077.58 282574.31]
 [1.0 1.0 0.0 91749.16 114175.79 294919.57]
 [1.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [1.0 0.0 1.0 78389.47 153773.43 299737.29]
 [1.0 1.0 0.0 73994.56 122782.75 3

In [22]:
import statsmodels.api as sm
X_opt = np.array(X[:, [0,1,2,3,4,5]], dtype=float)
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

C:\Users\Hamza\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Sun, 07 Feb 2021   Prob (F-statistic):           1.34e-27
Time:                        19:15:09   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.013e+04   6884.820      7.281      0.000    3.62e+04     6.4e+04
x1           198.7888   3371.007      0.059      0.953   -6595.030    6992.607
x2           -41.8870   3256.039     -0.013      0.990   -6604.003    6520.229
x3             0.8060      0.046     17.369      0.000       0.712       0.900
x4            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x5             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.45e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [23]:
# Remove x2: p-value(x2)=0.990
X_opt = np.array(X[:, [0,1,3,4,5]], dtype=float)
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Sun, 07 Feb 2021   Prob (F-statistic):           8.49e-29
Time:                        19:15:09   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.011e+04   6647.870      7.537      0.000    3.67e+04    6.35e+04
x1           220.1585   2900.536      0.076      0.940   -5621.821    6062.138
x2             0.8060      0.046     17.606      0.000       0.714       0.898
x3            -0.0270      0.052     -0.523      0.604      -0.131       0.077
x4             0.0270      0.017      1.592      0.118      -0.007       0.061
==============================================================================
Omnibus:                       14.758   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.172
Skew:                          -0.948   Prob(JB):                     2.53e-05
Kurtosis:                       5.563   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [24]:
# Remove x1: p-value(x1)=0.940
X_opt = np.array(X[:, [0,3,4,5]], dtype=float)
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Sun, 07 Feb 2021   Prob (F-statistic):           4.53e-30
Time:                        19:15:09   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.012e+04   6572.353      7.626      0.000    3.69e+04    6.34e+04
x1             0.8057      0.045     17.846      0.000       0.715       0.897
x2            -0.0268      0.051     -0.526      0.602      -0.130       0.076
x3             0.0272      0.016      1.655      0.105      -0.006       0.060
==============================================================================
Omnibus:                       14.838   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.442
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.586   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [25]:
# Remove x2: p-value(x2)=0.602
X_opt = np.array(X[:, [0,3,5]], dtype=float)
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Sun, 07 Feb 2021   Prob (F-statistic):           2.16e-31
Time:                        19:15:09   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.000    4.16e+04    5.24e+04
x1             0.7966      0.041     19.266      0.000       0.713       0.880
x2             0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [26]:
# Remove x2: p-value(x2)=0.060
X_opt = np.array(X[:, [0, 3]], dtype=float)
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Sun, 07 Feb 2021   Prob (F-statistic):           3.50e-32
Time:                        19:15:09   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.000    4.39e+04    5.41e+04
x1             0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [27]:
print(X_opt)

[[1.00e+00 1.65e+05]
 [1.00e+00 1.63e+05]
 [1.00e+00 1.53e+05]
 [1.00e+00 1.44e+05]
 [1.00e+00 1.42e+05]
 [1.00e+00 1.32e+05]
 [1.00e+00 1.35e+05]
 [1.00e+00 1.30e+05]
 [1.00e+00 1.21e+05]
 [1.00e+00 1.23e+05]
 [1.00e+00 1.02e+05]
 [1.00e+00 1.01e+05]
 [1.00e+00 9.39e+04]
 [1.00e+00 9.20e+04]
 [1.00e+00 1.20e+05]
 [1.00e+00 1.15e+05]
 [1.00e+00 7.80e+04]
 [1.00e+00 9.47e+04]
 [1.00e+00 9.17e+04]
 [1.00e+00 8.64e+04]
 [1.00e+00 7.63e+04]
 [1.00e+00 7.84e+04]
 [1.00e+00 7.40e+04]
 [1.00e+00 6.75e+04]
 [1.00e+00 7.70e+04]
 [1.00e+00 6.47e+04]
 [1.00e+00 7.53e+04]
 [1.00e+00 7.21e+04]
 [1.00e+00 6.61e+04]
 [1.00e+00 6.56e+04]
 [1.00e+00 6.20e+04]
 [1.00e+00 6.11e+04]
 [1.00e+00 6.34e+04]
 [1.00e+00 5.55e+04]
 [1.00e+00 4.64e+04]
 [1.00e+00 4.60e+04]
 [1.00e+00 2.87e+04]
 [1.00e+00 4.41e+04]
 [1.00e+00 2.02e+04]
 [1.00e+00 3.86e+04]
 [1.00e+00 2.88e+04]
 [1.00e+00 2.79e+04]
 [1.00e+00 2.36e+04]
 [1.00e+00 1.55e+04]
 [1.00e+00 2.22e+04]
 [1.00e+00 1.00e+03]
 [1.00e+00 1.32e+03]
 [1.00e+00 0.

In [28]:
regressor_opt = LinearRegression()
regressor_opt.fit(Xtrain[:,2:3], ytrain)
ypred_opt = regressor_opt.predict(Xtest[:,2:3])

In [29]:
print(ypred_opt)

[[ 73228.08]
 [101709.66]
 [113135.13]
 [111991.84]
 [103997.62]
 [146718.86]
 [ 68846.7 ]
 [135913.62]
 [172294.58]
 [ 88016.92]]


In [30]:
print(ypred)

[[ 73993.76]
 [ 99619.39]
 [111060.94]
 [114693.82]
 [101772.36]
 [146177.42]
 [ 69566.63]
 [135511.4 ]
 [173489.43]
 [ 89966.61]]


In [31]:
print(ytest)

[[ 78239.91]
 [ 99937.59]
 [105733.54]
 [110352.25]
 [107404.34]
 [129917.04]
 [ 71498.49]
 [146121.95]
 [182901.99]
 [ 96479.51]]


## Evaluating the model

In [32]:
from sklearn.metrics import r2_score

In [36]:
r2 = r2_score(ytest,ypred)
print('for the naive model:',r2)

for the naive model: 0.9374594482427873


In [37]:
r2 = r2_score(ytest,ypred_opt)
print('with the backward feature selection:',r2)

with the backward feature selection: 0.9306588722663609
