1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Print the numpy version and the configuration

In [3]:
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Hamza/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Hamza/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Hamza/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

3. Create a null vector of size 10

In [4]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to get the documentation of the numpy add function from the command line?

In [5]:
# python -c "import numpy; numpy.info(numpy.add)"
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

5. Create a null vector of size 10 but the fifth value which is 1

In [7]:
z = np.zeros(10)
z[4] = 1
print(z)
z

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

6. Create a vector with values ranging from 10 to 49

In [8]:
vrange = np.arange(10,50)
print(vrange)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


7. Reverse a vector (first element becomes last) (★☆☆)

In [13]:
vect = np.arange(1,11)
print('vector before :',vect)
vect = vect[::-1]
print('vector after :', vect)

vector before : [ 1  2  3  4  5  6  7  8  9 10]
vector after : [10  9  8  7  6  5  4  3  2  1]


8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
matrix = np.arange(0,9).reshape((3,3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

numpy.nonzero(a)
Return the indices of the elements that are non-zero.

Returns a tuple of arrays, one for each dimension of a, containing the indices of the non-zero elements in that dimension. The values in a are always tested and returned in row-major, C-style order.

In [22]:
# v = np.array([1,2,0,0,4,0])
# nz = v[v != 0]
# print(nz)
########
x = np.array([1,2,0,0,4,0])
nz = np.nonzero(x)
print('index of non-zeros :',nz)
print(x[nz])

index of non-zeros : (array([0, 1, 4], dtype=int64),)
[1 2 4]


10. Create a 3x3 identity matrix (★☆☆)

In [25]:
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


11. Create a 3x3x3 array with random values (★☆☆)

In [35]:
rm = np.random.random((3,3,3))
rm2 = np.random.rand(3,3,3)
print(rm)
print('---------------------------------------------------------')
print(rm2)

[[[0.86865723 0.98776239 0.26447884]
  [0.52892027 0.50090164 0.67532746]
  [0.87807548 0.93413617 0.23556858]]

 [[0.00357365 0.46654898 0.83568403]
  [0.79681915 0.06934407 0.64776729]
  [0.46234237 0.50054871 0.92275964]]

 [[0.66780054 0.76217885 0.56380131]
  [0.85209954 0.84830557 0.55321643]
  [0.83953547 0.74324691 0.00266141]]]
---------------------------------------------------------
[[[2.25049922e-01 5.30390424e-01 7.29810587e-01]
  [2.93350362e-01 6.12240991e-01 4.91998273e-01]
  [1.46979106e-01 5.76671198e-01 3.10067339e-01]]

 [[3.52420208e-01 8.29716862e-01 3.72950049e-02]
  [5.13297354e-01 3.99849557e-01 7.97016561e-01]
  [2.88154559e-01 8.83145607e-01 5.10261038e-04]]

 [[6.09842651e-01 9.77032048e-01 2.50865292e-01]
  [3.37297099e-01 3.84659344e-01 7.33076733e-01]
  [1.46243085e-01 2.42882676e-01 5.23141472e-01]]]


12. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [40]:
rm = np.random.random((10,10))
rMax, rMin = rm.max(), rm.min()
print('random matrix:', rm)
print('----------------------------------------------------------')
print('maximum :', rMax)
print('minimum :', rMin)

random matrix: [[2.23165424e-01 6.39171700e-01 1.15776644e-01 5.14242906e-01
  2.48469194e-02 1.16605697e-01 6.96463134e-01 2.66400035e-01
  8.71841486e-01 2.42811211e-01]
 [1.54049406e-01 2.65539847e-01 4.24232634e-01 4.44135327e-01
  5.57566828e-04 9.05030203e-01 2.19348921e-01 3.75293588e-01
  5.75258627e-01 8.60555685e-01]
 [7.55397987e-01 7.59935749e-01 3.90704998e-01 3.08831251e-01
  2.87239019e-02 3.01723289e-01 2.05363067e-02 5.46984473e-02
  4.31745641e-01 6.16738136e-01]
 [2.12041853e-01 3.19303505e-01 8.97589891e-01 1.71620650e-01
  3.98559370e-01 8.03852875e-01 6.67967724e-01 4.86740843e-01
  6.44672340e-01 7.27762689e-01]
 [4.76462170e-01 1.25182653e-01 3.56287834e-01 7.37151116e-01
  9.41986411e-01 8.39419475e-01 5.35546404e-01 8.63105466e-01
  7.62994093e-01 3.44274805e-01]
 [6.42286410e-01 5.86105266e-01 3.03695879e-01 6.80343978e-01
  3.91999358e-01 6.41422482e-01 1.05130506e-01 8.85342741e-02
  5.73682926e-01 9.47819793e-01]
 [4.17855087e-01 6.11571655e-01 5.73898341e

13. Create a random vector of size 30 and find the mean value (★☆☆)

In [41]:
rv = np.random.random(30)
rMean = rv.mean()
print('random vector:', rv)
print('----------------------------------------------------------')
print('vector mean :', rMean)

random vector: [0.63285303 0.00599189 0.64008184 0.63612183 0.9832476  0.95231984
 0.02343964 0.39683616 0.38471482 0.24855496 0.96078097 0.930262
 0.33546892 0.02939702 0.85998749 0.27892197 0.01369727 0.99216442
 0.96687079 0.93721807 0.69307725 0.01308403 0.93122852 0.11198814
 0.60216763 0.94720648 0.44755931 0.50953499 0.48611149 0.5890878 ]
----------------------------------------------------------
vector mean : 0.5513325385425794


14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [43]:
arr2d = np.zeros((5,5))
arr2d[0, :] = 1
arr2d[-1, :] = 1
arr2d[:, 0] = 1
arr2d[:, -1] = 1
print(arr2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
z = np.ones((10,10))
z[1:-1, 1:-1] = 0
print(z)

15. What is the result of the following expression? (★☆☆)

In [53]:
# 0 * np.nan #0 --> nan
# np.nan == np.nan #True --> False
# np.inf > np.nan #Error --> False
# np.nan - np.nan # np.nan
0.3 == 3*0.1 #True --> False:(Discussion)https://www.sololearn.com/Discuss/1477626/error-in-python-0-1-0-2-not-equal-0-3

False

16. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [54]:
z = np.diag(1+np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [58]:
z = np.ones((8,8))
z[0::2, 0::2] = 0
z[1::2, 1::2] = 0
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [57]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [62]:
z = np.arange(1,6*7*8+1).reshape((6,7,8))
print(np.where(z == 100))

(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))


In [63]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [64]:
np.info(np.unravel_index)

 unravel_index(*args, **kwargs)

unravel_index(indices, shape, order='C')

Converts a flat index or array of flat indices into a tuple
of coordinate arrays.

Parameters
----------
indices : array_like
    An integer array whose elements are indices into the flattened
    version of an array of dimensions ``shape``. Before version 1.6.0,
    this function accepted just one index value.
shape : tuple of ints
    The shape of the array to use for unraveling ``indices``.

    .. versionchanged:: 1.16.0
        Renamed from ``dims`` to ``shape``.

order : {'C', 'F'}, optional
    Determines whether the indices should be viewed as indexing in
    row-major (C-style) or column-major (Fortran-style) order.

    .. versionadded:: 1.6.0

Returns
-------
unraveled_coords : tuple of ndarray
    Each array in the tuple has the same shape as the ``indices``
    array.

See Also
--------
ravel_multi_index

Examples
--------
>>> np.unravel_index([22, 41, 37], (7,6))
(array([3, 6, 6]), array([4, 5, 1])

19. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [66]:
cb = np.array([[0,1],[1,0]], dtype=int)
print(np.tile(cb,(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Normalize a 5x5 random matrix (★☆☆)

In [68]:
n = np.random.randn(5,5)
print(n)

[[-0.12295964  0.77840221  0.36295057 -0.56053609 -0.32639418]
 [-1.81709673 -1.50291621 -0.73900586  0.26934517 -0.79001375]
 [-0.02650774 -1.34615143  0.47724705 -1.11836528 -1.82727932]
 [ 0.94558282 -1.58474402 -0.43134886 -0.48339183 -1.85721773]
 [ 0.77527244 -0.01428936 -0.28383019  0.29698745 -1.06282421]]
